[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dynamicxs"
authors = [{name = "Nina", email = "nandrejevic@alum.mit.edu"}]
dynamic = ["version", "description"]
